### ISSUE TITLE
这个插件没有添加extract: false，又由于后编译，页面多的时候导致build的时候堆爆了

### ISSUE THREAD

**Issue by hezhongfeng** [cube-ui/vue-cli-plugin-cube-ui#4]
需要在`vue.config.js`添加[css配置](https://cli.vuejs.org/zh/config/#css-extract)
```
css.extract: false
```
害惨我了，找了很久的时间才找到这里的问题，建议尽快发布个新版
[https://github.com/vuejs/vue-cli/issues/3091](https://github.com/vuejs/vue-cli/issues/3091)

**Comment by dolymood** [comment]
看了下你说的那个 issue，目测一般情况下不会出现，可能因为你们项目本身大所以出现了这个问题，这个可以在 vue.config.js 中直接配置即可。

不过还是要多谢反馈，以防其他人会遇到类似的坑，好像说的那个限制问题，webpack好像是已知的 issue，目前只能通过这种方式解决了，待相关插件修复后可正常使用。

**Comment by hezhongfeng** [comment]
根本原因是webpack抽离css的问题，间接原因是后编译后超大的css和我们本身项目比较大的原因，但还是建议加上这个设置，因为在`vue-cli < 3`的里面提到了这个，所以目前的项目并没有问题，我先关掉了。
